version: '3.8'

services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: complyVault
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poojitha
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Microservices
  ingestion-service:
    build:
      context: ./IngestionAndValidation
      dockerfile: Dockerfile
    container_name: ingestion-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
      - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/complyVault
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres
    volumes:
      - ./IngestionAndValidation/logs:/app/logs

  normalizer-service:
    build:
      context: ./normalizer
      dockerfile: Dockerfile
    container_name: normalizer-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/complyVault
    volumes:
      - ./normalizer/data:/app/data

  compliance-service:
    build:
      context: ./Compliance
      dockerfile: Dockerfile
    container_name: compliance-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mongodb
      - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/complyVault
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres

  search-service:
    build:
      context: ./Search
      dockerfile: Dockerfile
    container_name: search-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - elasticsearch
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200

  review-service:
    build:
      context: ./review
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres

  retention-service:
    build:
      context: ./Retention
      dockerfile: Dockerfile
    container_name: retention-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/complyVault
    volumes:
      - ./Retention/data:/app/data

  audit-service:
    build:
      context: ./Audit
      dockerfile: Dockerfile
    container_name: audit-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/complyVault

volumes:
  mongodb_data:
  postgres_data:
