apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-deployment
  labels:
    app: compliance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
        - name: compliance
          image: compliance-service:1.0
          ports:
            - containerPort: 8082
          env:
            - name: AUDIT_SERVICE_URL
              value: "http://audit-service:8093"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/compliance"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
