apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalizer-deployment
  labels:
    app: normalizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalizer
  template:
    metadata:
      labels:
        app: normalizer
    spec:
      containers:
        - name: normalizer
          image: normalizer-service:1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-service:27017/complyvault_normalizer"
            - name: AUDIT_SERVICE_URL
              value: "http://audit-service:8093"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
