apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTQ2WkRGTVU2WENGSk9URU4=
  AWS_SECRET_ACCESS_KEY: a05WT2JPNURSUXBLaFFsaU9SMGl6c3YrWmpYd0ZUK1p6a3htcWxiNw==
